### ISSUE TITLE
Query with where and Filter or doesn't work

### ISSUE THREAD

**Issue by Thibault4** [atn832/fake_cloud_firestore#320]
```
# Constants File
static late CollectionReference usersRef;

# In flutter test widget init
QueryUtils.usersRef = fakeFirestore.collection('users');

# In my widget
final audience = await QueryUtils.usersRef
        .where(Filter.or(Filter('department', isEqualTo: search),
            Filter('city', isEqualTo: search)))
        .count()
        .get(); ====> Throw error
```
Stacktrace
```
Unsupported

When the exception was thrown, this was the stack:
#0      MockQuery._valueMatchesQuery (package:fake_cloud_firestore/src/mock_query.dart:409:5)
#1      MockQuery.where.<anonymous closure>.<anonymous closure> (package:fake_cloud_firestore/src/mock_query.dart:275:18)
#2      WhereIterator.moveNext (dart:_internal/iterable.dart:451:13)
#3      new _GrowableList._ofOther (dart:core-patch/growable_array.dart:202:26)
#4      new _GrowableList.of (dart:core-patch/growable_array.dart:152:26)
#5      new List.of (dart:core-patch/array_patch.dart:39:18)
#6      Iterable.toList (dart:core/iterable.dart:498:7)
#7      MockQuery.where.<anonymous closure> (package:fake_cloud_firestore/src/mock_query.dart:287:12)
#8      MockQuery.get (package:fake_cloud_firestore/src/mock_query.dart:47:29)
<asynchronous suspension>
#9      FakeAggregateQuery.get (package:fake_cloud_firestore/src/fake_aggregate_query.dart:21:22)
<asynchronous suspension>

```

That code throw and error : Unsupported. I try also to remove count by same error.

Thanks for ur work 🙏

**Comment by Thibault4** [comment]
I just upgrade package to 3.1.0 who support filters and that work not.

Greatfull !!!!! Thanks
